# Generated by Django 5.0.4 on 2024-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime_name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('episodes', models.IntegerField()),
                ('episodes_watched', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
